Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2020-12, with the labels that each got.

#4441 Pull request n1 from fork
  test1
Labels: high

#4442 Pull request n2 from fork
  test2
Labels: medium

#4448 Pull request n1 from main
  test1
Labels: ready

#4451 Pull request n1 from main
  test1
Labels: ready

#4456 Pull request n3 from main
  test3
Labels: ready

#4461 Pull request n3 from fork
  test3
Labels: low

#4460 Pull request n2 from fork
  test2
Labels: medium

#4489 Pull request n1 from main
  test1
Labels: ready

#4492 Pull request n1 from main
  test1
Labels: ready

#4502 Pull request n1 from main
  test1
Labels: ready

#4505 Pull request n1 from main
  test1
Labels: ready

#4512 Pull request n1 from main
  test1
Labels: ready

#4515 Pull request n1 from main
  test1
Labels: ready

#4528 Pull request n1 from main
  test1
Labels: ready

#4531 Pull request n1 from main
  test1
Labels: ready

#4534 Pull request n1 from main
  test1
Labels: ready

#4537 Pull request n1 from main
  test1
Labels: ready

#4540 Pull request n1 from main
  test1
Labels: ready

#4543 Pull request n1 from main
  test1
Labels: ready

#4692 Pull request n2 from fork
  test2
Labels: queue

#4831 Pull request n2 from fork
  test2
Labels: queue

#4852 Pull request n2 from fork
  test2
Labels: queue

#4860 Pull request n2 from fork
  test2
Labels: queue
