Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-06, with the labels that each got.

#12581 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#12625 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#12626 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#12636 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#12650 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12679 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#12704 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#12718 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12741 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#12776 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#12790 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12812 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#12827 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12832 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12837 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12854 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12860 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12878 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12884 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12894 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12948 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#13001 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#13095 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#13131 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#13199 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#13224 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#13230 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#13361 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#13362 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#13402 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#13405 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#13410 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#13553 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#13554 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#13560 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#13563 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#13568 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#13585 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#13599 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#13622 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#13796 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#13797 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#13803 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#13806 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#13811 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#13828 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#13841 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#13859 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent
