Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-10, with the labels that each got.

#16511 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#16512 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#16521 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#16524 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#16529 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#16539 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16540 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16548 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#16549 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16569 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#16580 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#16606 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent
