Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-05, with the labels that each got.

#10795 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#10837 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11063 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11086 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11092 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11128 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11134 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11140 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11157 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11180 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#11321 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#11322 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#11328 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#11331 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#11336 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#11353 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11367 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11390 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#11435 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11441 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11907 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#11908 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#11914 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#11917 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#11922 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#11939 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#11956 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#11979 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#12111 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#12117 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12309 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#12310 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#12316 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#12319 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#12324 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#12341 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#12355 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#12378 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent
