Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-08, with the labels that each got.

#15457 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15507 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15520 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15560 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15570 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#15598 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#15627 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15638 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#15661 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#15752 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15753 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15761 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15762 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15835 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#15836 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#15842 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#15845 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#15850 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#15856 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15857 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15873 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15874 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15882 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15883 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15891 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15892 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15942 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#15943 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15952 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15953 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15961 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15962 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15970 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15971 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#15991 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#15992 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16000 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16001 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16009 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#16032 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#16033 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16042 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#16056 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#16057 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16082 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16083 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16091 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#16092 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16105 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16106 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16114 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#16115 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16127 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#16137 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#16159 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#16179 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16180 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16188 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16189 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16229 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#16230 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16238 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#16239 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#16326 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#16327 test_merge_priority: pull request n2 from fork
  test2
Labels: medium
