Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-01, with the labels that each got.

#4897 Pull request n2 from fork
  test2
Labels: queue

#4960 Pull request n1 from fork
  test1
Labels: queue

#4967 Pull request n1 from fork
  test1
Labels: queue

#4982 Pull request n1 from fork
  test1
Labels: queue

#5005 Pull request n1 from fork
  test1
Labels: queue

#5012 Pull request n1 from fork
  test1
Labels: queue

#5313 Pull request n1 from fork
  test1
Labels: queue

#5325 Pull request n1 from fork
  test1
Labels: queue

#5343 Pull request n1 from fork
  test1
Labels: queue

#5360 Pull request n1 from fork
  test1
Labels: queue

#5383 Pull request n1 from fork
  test1
Labels: high

#5384 Pull request n2 from fork
  test2
Labels: medium

#5426 Pull request n1 from fork
  test1
Labels: queue

#5438 Pull request n1 from fork
  conflicts
Labels: queue

#5450 Pull request n1 from fork
  test1
Labels: queue

#5495 Pull request n1 from fork
  test1
Labels: queue

#5508 Pull request n1 from fork
  test1
Labels: queue

#5515 Pull request n1 from fork
  test1
Labels: queue

#5554 Pull request n1 from fork
  conflicts
Labels: queue

#5589 Pull request n1 from fork
  test1
Labels: queue

#5857 Pull request n1 from fork
  test1
Labels: high

#5858 Pull request n2 from fork
  test2
Labels: medium

#5864 Pull request n1 from main
  test1
Labels: ready

#5867 Pull request n1 from main
  test1
Labels: ready

#5872 Pull request n3 from main
  test3
Labels: ready

#5877 Pull request n3 from fork
  test3
Labels: low

#5876 Pull request n2 from fork
  test2
Labels: medium

#5935 Pull request n1 from fork
  test1
Labels: queue

#5941 Pull request n1 from fork
  test1
Labels: queue

#5949 Pull request n1 from fork
  test1
Labels: queue

#5981 Pull request n1 from fork
  test1
Labels: queue

#5988 Pull request n1 from fork
  test1
Labels: queue

#6007 Pull request n1 from fork
  test1
Labels: queue

#6108 Pull request n1 from fork
  test1
Labels: queue

#6207 Pull request n1 from fork
  test1
Labels: queue

#6252 Pull request n1 from fork
  test1
Labels: queue

#6278 Pull request n1 from fork
  test1
Labels: queue

#6300 Pull request n1 from fork
  test1
Labels: queue

#6334 Pull request n1 from fork
  test1
Labels: queue

#6383 Pull request n1 from fork
  test1
Labels: queue

#6405 Pull request n1 from fork
  test1
Labels: queue

#6454 Pull request n1 from fork
  test1
Labels: queue

#6524 Pull request n1 from fork
  test1
Labels: queue

#6573 Pull request n1 from fork
  test1
Labels: queue

#6585 Pull request n1 from fork
  test1
Labels: queue

#6630 Pull request n1 from fork
  test1
Labels: queue

#6642 Pull request n1 from fork
  test1
Labels: queue

#6747 Pull request n1 from fork
  test1
Labels: queue
