Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-02, with the labels that each got.

#6859 Pull request n1 from fork
  test1
Labels: high

#6860 Pull request n2 from fork
  test2
Labels: medium

#6866 Pull request n1 from main
  test1
Labels: ready

#6869 Pull request n1 from main
  test1
Labels: ready

#6874 Pull request n3 from main
  test3
Labels: ready

#6879 Pull request n3 from fork
  test3
Labels: low

#6878 Pull request n2 from fork
  test2
Labels: medium

#6889 Pull request n1 from fork
  test1
Labels: queue

#7017 Pull request n1 from fork
  test1
Labels: queue

#7032 Pull request n1 from fork
  test1
Labels: queue

#7275 Pull request n1 from fork
  test1
Labels: queue

#7339 Pull request n2 from fork
  test2
Labels: queue

#7412 Pull request n3 from fork
  test3
Labels: low

#7411 Pull request n2 from fork
  test2
Labels: medium
