Repository mergifyio-testing/functional-testing-repo, pull requests merged in 2021-07, with the labels that each got.

#13996 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14010 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14016 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14022 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14028 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14034 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14040 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14046 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14052 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14100 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14120 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14128 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14142 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14301 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#14302 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#14308 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#14311 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#14316 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14333 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14347 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14370 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#14431 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14437 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14463 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#14466 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#14471 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14482 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14485 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14488 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14578 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#14581 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#14586 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14719 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#14720 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#14751 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14761 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14784 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#14838 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#14841 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#14848 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14858 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14894 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#14898 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#14913 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14923 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14933 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#14991 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#14992 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#14998 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#15001 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#15011 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15021 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#15043 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#15058 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#15061 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#15071 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15081 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#15113 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#15114 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#15122 test_merge_smart_legacy: pull request n1 from main
  test1
Labels: ready

#15125 test_merge_smart_ordered: pull request n1 from main
  test1
Labels: ready

#15130 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#15133 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#15137 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#15140 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready

#15145 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15155 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#15177 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#15195 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#15201 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#15239 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#15328 test_merge_smart_unordered: pull request n3 from main
  test3
Labels: ready
